/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BufferResult {
  buffer: Buffer
  result: number
}

export declare function engineClearBuffer(id: number): number

export declare function engineDispose(): number

export declare function engineDownloadBuffer(id: number): BufferResult

export declare function engineInit(): number

export declare function engineReceiveQueue(): BufferResult

export declare function engineSendQueue(data: Buffer): number

export declare function engineTick(time: number, deltaTime: number): number

export declare function engineUploadBuffer(id: number, data: Buffer): number
