#[derive(Debug, Clone, Default)]
pub struct TickProfiling {
    pub command_processing_ns: u64,
    pub gamepad_processing_ns: u64,
    pub event_loop_pump_ns: u64,
    pub request_redraw_ns: u64,
    pub serialization_ns: u64,
    pub render_total_ns: u64,
    pub render_shadow_ns: u64,
    pub render_windows_ns: u64,
    pub frame_delta_ns: u64,
    pub total_events_dispatched: usize,
    pub total_events_cached: usize,
    pub custom_events_ns: u64,
    pub gpu_shadow_ns: u64,
    pub gpu_light_cull_ns: u64,
    pub gpu_forward_ns: u64,
    pub gpu_compose_ns: u64,
    pub gpu_total_ns: u64,
}
