import * as VULFRAM_CORE from './napi';
import { pack, unpack } from 'msgpackr';
import type { VulframResult } from './enums';
import type { EngineBatchCmds, EngineBatchEvents } from './cmds';

export * from './cmds';
export * from './dev';
export * from './enums';
export * from './events';

/**
 * Initializes the Vulfram game engine.
 * Must be called before any other engine operations.
 *
 * @example
 * ```typescript
 * const result = vulframInit();
 * if (result === VulframResult.Success) {
 *   console.log('Engine initialized successfully');
 * }
 * ```
 */
export function vulframInit(): VulframResult {
  return VULFRAM_CORE.engineInit();
}

/**
 * Disposes the Vulfram engine and releases all resources.
 * Should be called when shutting down the application.
 *
 * @example
 * ```typescript
 * vulframDispose();
 * console.log('Engine disposed');
 * ```
 */
export function vulframDispose(): VulframResult {
  return VULFRAM_CORE.engineDispose();
}

/**
 * Sends a batch of commands to the engine for execution.
 * Commands are processed in the order they are sent.
 *
 * @example
 * ```typescript
 * const batch: EngineBatchCmds = {
 *   cmds: [{
 *     type: 'cmd-window-create',
 *     content: {
 *       title: 'My Game',
 *       size: { width: 1280, height: 720 },
 *       position: { x: 100, y: 100 },
 *       borderless: false,
 *       resizable: true,
 *       initialState: 'normal'
 *     }
 *   }]
 * };
 * vulframSendQueue(batch);
 * ```
 */
export function vulframSendQueue(batch: EngineBatchCmds): VulframResult {
  const buffer = pack(batch);
  return VULFRAM_CORE.engineSendQueue(Buffer.from(buffer));
}

/**
 * Receives and processes events from the engine.
 * Returns a batch of events that occurred since the last call.
 *
 * @example
 * ```typescript
 * const [events, result] = vulframReceiveQueue();
 * if (result === VulframResult.Success) {
 *   for (const event of events.events) {
 *     if (event.kind === 'window') {
 *       console.log('Window event:', event.content);
 *     }
 *   }
 * }
 * ```
 */
export function vulframReceiveQueue(): [EngineBatchEvents, VulframResult] {
  const { buffer, result } = VULFRAM_CORE.engineReceiveQueue();
  const events = unpack(buffer) as EngineBatchEvents;
  return [events, result];
}

/**
 * Advances the engine by one frame tick.
 * Should be called once per frame in your game loop.
 *
 * @example
 * ```typescript
 * let lastTime = Date.now();
 *
 * function gameLoop() {
 *   const currentTime = Date.now();
 *   const deltaTime = currentTime - lastTime;
 *   lastTime = currentTime;
 *
 *   vulframTick(currentTime, deltaTime);
 *   requestAnimationFrame(gameLoop);
 * }
 * ```
 */
export function vulframTick(time: number, deltaTime: number): VulframResult {
  return VULFRAM_CORE.engineTick(time, deltaTime);
}

/**
 * Uploads a buffer to the engine for GPU processing.
 * Used for textures, meshes, and other GPU resources.
 *
 * @example
 * ```typescript
 * const imageData = new Uint8Array([...]);
 * const bufferId = 1;
 *
 * const result = vulframUploadBuffer(bufferId, imageData);
 * if (result === VulframResult.Success) {
 *   console.log('Buffer uploaded successfully');
 * }
 * ```
 */
export function vulframUploadBuffer(
  id: number,
  buffer: Uint8Array,
): VulframResult {
  return VULFRAM_CORE.engineUploadBuffer(id, Buffer.from(buffer));
}

/**
 * Downloads a buffer from the engine.
 * Retrieves data that was previously uploaded or generated by the GPU.
 *
 * @example
 * ```typescript
 * const bufferId = 1;
 * const [data, result] = vulframDownloadBuffer(bufferId);
 *
 * if (result === VulframResult.Success) {
 *   console.log('Downloaded', data.length, 'bytes');
 * }
 * ```
 */
export function vulframDownloadBuffer(id: number): [Uint8Array, VulframResult] {
  const { buffer, result } = VULFRAM_CORE.engineDownloadBuffer(id);
  return [buffer, result];
}

/**
 * Clears a buffer from the engine, freeing its GPU memory.
 * Should be called when a buffer is no longer needed.
 *
 * @example
 * ```typescript
 * const bufferId = 1;
 * vulframClearBuffer(bufferId);
 * console.log('Buffer cleared');
 * ```
 */
export function vulframClearBuffer(id: number): VulframResult {
  return VULFRAM_CORE.engineClearBuffer(id);
}
